"""OOP & protocols — a mini-domain with a Protocol and two implementations.

The point: SlackNotifier and EmailNotifier NEVER import or mention the
Notifier protocol. They satisfy it structurally — duck typing, but mypy
verifies it. This is the idea that replaces `interface`/`implements`.

Run it:
    uv run python 04-oop-classes-and-protocols/notifiers.py
"""

from dataclasses import dataclass, field
from typing import Protocol


# --- The contract: structural, not nominal -----------------------------------
class Notifier(Protocol):
    """≈ a Java interface — but implementations don't have to name it."""

    def send(self, recipient: str, message: str) -> str:
        """Deliver a message; return a delivery receipt."""
        ...  # `...` = no body, like an interface method


# --- Two implementations. Note: no `implements`, no import of Notifier --------
@dataclass
class EmailNotifier:
    smtp_host: str = "smtp.example.com"

    def send(self, recipient: str, message: str) -> str:
        return f"email to {recipient} via {self.smtp_host}: {message}"


@dataclass
class SlackNotifier:
    channel: str = "#alerts"

    def send(self, recipient: str, message: str) -> str:
        return f"slack {self.channel} (cc {recipient}): {message}"


# --- The consumer depends on the abstraction, exactly like Java ----------------
def notify_all(notifiers: list[Notifier], recipient: str, message: str) -> list[str]:
    """mypy checks that every element has a matching .send() — structurally."""
    return [n.send(recipient, message) for n in notifiers]


# --- A dataclass with the usual Object methods, for free -----------------------
@dataclass(frozen=True)  # frozen ≈ a Java record: immutable + hashable
class Task:
    title: str
    estimate: int = 1
    tags: tuple[str, ...] = ()  # tuple, not list: frozen dataclasses need hashable fields

    @property
    def is_big(self) -> bool:
        """≈ a getter, but called without parens: task.is_big"""
        return self.estimate >= 5


@dataclass
class TaskBoard:
    """A mutable counterpart, with a default factory (≈ field initializer)."""

    name: str
    tasks: list[Task] = field(default_factory=list)  # fresh list per instance

    def add(self, task: Task) -> None:
        self.tasks.append(task)

    def __str__(self) -> str:  # ≈ toString()
        return f"TaskBoard({self.name!r}, {len(self.tasks)} tasks)"


def main() -> None:
    notifiers: list[Notifier] = [EmailNotifier(), SlackNotifier(channel="#backend")]
    for receipt in notify_all(notifiers, recipient="oncall@example.com", message="deploy done"):
        print(receipt)

    task = Task(title="migrate to uv", estimate=5, tags=("tooling",))
    print(f"\n{task!r}")  # __repr__ — generated by @dataclass
    print(f"is_big (property): {task.is_big}")
    print(f"equality (generated __eq__): {task == Task('migrate to uv', 5, ('tooling',))}")

    board = TaskBoard(name="backend")
    board.add(task)
    print(f"\n{board}")  # __str__ — hand-written


if __name__ == "__main__":
    main()
